// Tweak definitions. risk: 1 zero, 2 low, 3 medium, 4 extreme.
// Actions: reg (key, name, type, data), service (name, optional), power, appx (names).
const CV = 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion', CDM = CV + '\\ContentDeliveryManager';
const SP = 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile';
const POL = 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows', CTL = 'HKLM\\SYSTEM\\CurrentControlSet\\Control';
const GB = 'HKCU\\Software\\Microsoft\\GameBar', GCS = 'HKCU\\System\\GameConfigStore';
const dw = (key, name, data) => ({ t: 'reg', key, name, type: 'REG_DWORD', data });
const sz = (key, name, data) => ({ t: 'reg', key, name, type: 'REG_SZ', data: String(data) });
const svc = (name, optional) => ({ t: 'service', name, optional });
const appx = (...names) => ({ t: 'appx', names });
const T = (id, cat, risk, name, desc, actions, extra) => ({ id, cat, risk, name, desc, actions, ...extra });
const SO = { after: 'Sign out needed' }, RS = { after: 'Restart needed' }, NU = { reversible: false };

module.exports = [
  // Performance
  T('game-mode', 'performance', 1, 'Game Mode', 'Tells Windows to favour the foreground game and hold back updates and background work while you play.',
    [dw(GB, 'AutoGameModeEnabled', 1), dw(GB, 'AllowAutoGameMode', 1)]),
  T('game-dvr', 'performance', 1, 'Turn off background game capture', 'Stops Xbox Game Bar recording in the background. Manual recording still works.',
    [dw(GCS, 'GameDVR_Enabled', 0), dw(CV + '\\GameDVR', 'AppCaptureEnabled', 0)]),
  T('visual-effects', 'performance', 1, 'Turn off transparency and window animations', 'Frees a little GPU time on the desktop and makes windows open instantly.',
    [dw(CV + '\\Themes\\Personalize', 'EnableTransparency', 0), sz('HKCU\\Control Panel\\Desktop\\WindowMetrics', 'MinAnimate', 0)], SO),
  T('startup-delay', 'performance', 1, 'Remove the startup app delay', 'Desktop apps start right after sign-in instead of waiting several seconds.',
    [dw(CV + '\\Explorer\\Serialize', 'StartupDelayInMSec', 0)]),
  T('menu-delay', 'performance', 1, 'Open menus instantly', 'Removes the short pause before menus appear.',
    [sz('HKCU\\Control Panel\\Desktop', 'MenuShowDelay', 0)], SO),
  T('background-apps', 'performance', 2, 'Stop Store apps running in the background', 'Apps you closed no longer keep working and using memory.',
    [dw(CV + '\\BackgroundAccessApplications', 'GlobalUserDisabled', 1)]),
  T('fast-startup', 'performance', 2, 'Turn off Fast Startup', 'Shutdown becomes a real shutdown, so drivers and services start clean. Boots a few seconds slower on hard drives.',
    [dw(CTL + '\\Session Manager\\Power', 'HiberbootEnabled', 0)]),
  T('power-plan', 'performance', 2, 'Ultimate Performance power plan', 'Keeps the CPU at full speed instead of down-clocking between loads. Uses more power, so skip it on battery.',
    [{ t: 'power' }]),
  T('sys-responsiveness', 'performance', 2, 'Reserve less CPU for background media tasks', 'Lowers the reserved share from 20% to 10%. The effect is small.',
    [dw(SP, 'SystemResponsiveness', 10)]),
  T('games-priority', 'performance', 2, 'Raise scheduler priority for games', 'Gives tasks tagged as games higher CPU and disk priority in the multimedia scheduler.',
    [dw(SP + '\\Tasks\\Games', 'Priority', 6), sz(SP + '\\Tasks\\Games', 'Scheduling Category', 'High'), sz(SP + '\\Tasks\\Games', 'SFIO Priority', 'High')]),
  T('sysmain', 'performance', 3, 'Disable SysMain (Superfetch)', 'Stops preloading apps into RAM. Fine on an SSD, but apps may open slower from a hard drive.',
    [svc('SysMain')]),
  T('wsearch', 'performance', 3, 'Disable Windows Search indexing', 'Stops background file indexing. Search in Start and Explorer gets slower and may miss files.',
    [svc('WSearch')]),
  T('hags', 'performance', 3, 'Hardware-accelerated GPU scheduling', 'Lets the GPU manage its own scheduling. Helps some games, hurts others, so compare your 1% lows.',
    [dw(CTL + '\\GraphicsDrivers', 'HwSchMode', 2)], RS),
  T('fullscreen-opt', 'performance', 3, 'Disable fullscreen optimizations', 'Uses true exclusive fullscreen where games support it. Some run smoother, some stutter, so test per game.',
    [dw(GCS, 'GameDVR_FSEBehaviorMode', 2), dw(GCS, 'GameDVR_HonorUserFSEBehaviorMode', 1), dw(GCS, 'GameDVR_DXGIHonorFSEWindowsCompatible', 1)]),
  T('priority-sep', 'performance', 3, 'Favour the foreground app in CPU scheduling', 'Gives the active window longer, fixed time slices. Gains are small and vary by game, so benchmark it.',
    [dw(CTL + '\\PriorityControl', 'Win32PrioritySeparation', 38)]),
  T('power-throttling', 'performance', 3, 'Turn off power throttling', 'Stops Windows limiting CPU speed for background apps. Raises power use and heat, especially on laptops.',
    [dw(CTL + '\\Power\\PowerThrottling', 'PowerThrottlingOff', 1)]),
  T('vbs-off', 'performance', 4, 'Turn off Memory Integrity (VBS)', 'Can recover a few percent of FPS on some CPUs, but weakens protection against kernel-level malware.',
    [dw(CTL + '\\DeviceGuard\\Scenarios\\HypervisorEnforcedCodeIntegrity', 'Enabled', 0)], RS),

  // Input
  T('mouse-accel', 'input', 1, 'Disable mouse acceleration', 'Cursor and aim move exactly as far as your hand does, at any speed.',
    [sz('HKCU\\Control Panel\\Mouse', 'MouseSpeed', 0), sz('HKCU\\Control Panel\\Mouse', 'MouseThreshold1', 0), sz('HKCU\\Control Panel\\Mouse', 'MouseThreshold2', 0)], SO),
  T('sticky-keys', 'input', 1, 'Stop Sticky Keys and Filter Keys pop-ups', 'Tapping Shift five times mid-game no longer interrupts you with a dialog.',
    [sz('HKCU\\Control Panel\\Accessibility\\StickyKeys', 'Flags', 506), sz('HKCU\\Control Panel\\Accessibility\\Keyboard Response', 'Flags', 122), sz('HKCU\\Control Panel\\Accessibility\\ToggleKeys', 'Flags', 58)]),
  T('key-repeat', 'input', 1, 'Fastest key repeat', 'Shortest delay and fastest repeat rate for held keys.',
    [sz('HKCU\\Control Panel\\Keyboard', 'KeyboardDelay', 0), sz('HKCU\\Control Panel\\Keyboard', 'KeyboardSpeed', 31)], SO),
  T('gamebar-controller', 'input', 1, 'Stop the controller button opening Game Bar', 'The Xbox button on a controller no longer pops Game Bar over your game.',
    [dw(GB, 'UseNexusForGameBarEnabled', 0)]),
  T('timer-res', 'input', 3, 'Global timer resolution', 'Windows 11 only. Lets one app\'s fine timer request apply system-wide, which can tighten frame pacing but raises idle power use.',
    [dw(CTL + '\\Session Manager\\kernel', 'GlobalTimerResolutionRequests', 1)], RS),

  // Network
  T('delivery-opt', 'network', 2, 'Stop uploading updates to other PCs', 'Windows no longer shares update files over your connection.',
    [dw(POL + '\\DeliveryOptimization', 'DODownloadMode', 0)]),
  T('qos', 'network', 2, 'Remove the QoS bandwidth limit', 'Removes the optional cap on bandwidth for QoS traffic. Rarely noticeable on its own.',
    [dw(POL + '\\Psched', 'NonBestEffortLimit', 0)]),
  T('net-throttle', 'network', 3, 'Remove network throttling', 'Windows limits packet rate while media plays. Removing it can smooth online games, but the effect is small on current builds.',
    [dw(SP, 'NetworkThrottlingIndex', 4294967295)]),

  // Debloat and privacy
  T('ad-id', 'debloat', 1, 'Turn off advertising ID', 'Apps can no longer use a per-user ID to personalise ads.',
    [dw(CV + '\\AdvertisingInfo', 'Enabled', 0)]),
  T('suggestions', 'debloat', 1, 'Stop promoted apps and suggestions', 'Removes ads in Start and Settings and stops silent installs of sponsored apps.',
    [dw(CDM, 'SilentInstalledAppsEnabled', 0), dw(CDM, 'SystemPaneSuggestionsEnabled', 0), dw(CDM, 'SubscribedContent-338388Enabled', 0), dw(CDM, 'SubscribedContent-338389Enabled', 0)]),
  T('tips', 'debloat', 1, 'Turn off tips and welcome screens', 'Stops "get the most out of Windows" prompts and lock screen tips.',
    [dw(CDM, 'SoftLandingEnabled', 0), dw(CDM, 'SubscribedContent-338387Enabled', 0), dw(CDM, 'SubscribedContent-310093Enabled', 0), dw(CDM, 'SubscribedContent-338393Enabled', 0)]),
  T('web-search', 'debloat', 1, 'Keep Start search on your PC', 'Start search stops showing Bing web results.',
    [dw('HKCU\\Software\\Policies\\Microsoft\\Windows\\Explorer', 'DisableSearchBoxSuggestions', 1)], SO),
  T('telemetry-service', 'debloat', 2, 'Disable the telemetry service', 'Stops Connected User Experiences and Telemetry. Windows keeps working normally.',
    [svc('DiagTrack')]),
  T('telemetry-policy', 'debloat', 2, 'Send minimum diagnostic data', 'Asks Windows for the lowest telemetry level. Home and Pro editions treat 0 as the basic level.',
    [dw(POL + '\\DataCollection', 'AllowTelemetry', 0)]),
  T('activity-history', 'debloat', 2, 'Turn off activity history', 'Stops Windows recording and syncing the apps and files you open.',
    [dw(POL + '\\System', 'PublishUserActivities', 0), dw(POL + '\\System', 'UploadUserActivities', 0), dw(POL + '\\System', 'EnableActivityFeed', 0)]),
  T('error-reporting', 'debloat', 2, 'Turn off Windows Error Reporting', 'Crashes are no longer packaged and sent to Microsoft.',
    [dw('HKLM\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting', 'Disabled', 1)]),
  T('widgets', 'debloat', 2, 'Turn off Widgets', 'Removes the Widgets board and its background web process.',
    [dw('HKLM\\SOFTWARE\\Policies\\Microsoft\\Dsh', 'AllowNewsAndInterests', 0)], SO),
  T('wu-drivers', 'debloat', 3, 'Stop Windows Update replacing your GPU driver', 'Update drivers yourself from the vendor instead. Other Windows updates are unaffected.',
    [dw(POL + '\\WindowsUpdate', 'ExcludeWUDriversInQualityUpdate', 1)]),
  T('remove-apps', 'debloat', 3, 'Remove preinstalled apps', 'Removes News, Weather, Solitaire, Clipchamp, Get Help, Tips and Feedback Hub. Reinstall from the Store if you miss one.',
    [appx('Microsoft.BingNews', 'Microsoft.BingWeather', 'Microsoft.MicrosoftSolitaireCollection', 'Clipchamp.Clipchamp', 'Microsoft.GetHelp', 'Microsoft.Getstarted', 'Microsoft.WindowsFeedbackHub')], NU),
  T('remove-extra', 'debloat', 3, 'Remove extra Microsoft apps', 'Removes Teams, Phone Link, People, Mail, To Do, Power Automate and Quick Assist.',
    [appx('MicrosoftTeams', 'Microsoft.YourPhone', 'Microsoft.People', 'microsoft.windowscommunicationsapps', 'Microsoft.Todos', 'Microsoft.PowerAutomateDesktop', 'MicrosoftCorporationII.QuickAssist')], NU),
  T('xbox-services', 'debloat', 4, 'Disable Xbox background services', 'Breaks Game Pass, Xbox sign-in and some Microsoft Store games until you turn it off again.',
    [svc('XblAuthManager', 1), svc('XblGameSave', 1), svc('XboxNetApiSvc', 1), svc('XboxGipSvc', 1)]),
  T('remove-xbox', 'debloat', 4, 'Remove Xbox apps and Game Bar', 'Games that need Xbox sign-in stop working until you reinstall these from the Store.',
    [appx('Microsoft.XboxApp', 'Microsoft.GamingApp', 'Microsoft.XboxGamingOverlay', 'Microsoft.XboxIdentityProvider', 'Microsoft.XboxSpeechToTextOverlay')], NU),

  // More performance and fewer background processes
  T('taskbar-anim', 'performance', 1, 'Turn off taskbar animations', 'Taskbar buttons and flyouts appear without animating.',
    [dw(CV + '\\Explorer\\Advanced', 'TaskbarAnimations', 0)], SO),
  T('search-highlights', 'performance', 1, 'Turn off search highlights', 'Stops the daily illustrations and web content loading in the search box.',
    [dw(CV + '\\SearchSettings', 'IsDynamicSearchBoxEnabled', 0)]),
  T('track-progs', 'performance', 1, 'Stop tracking app launches', 'Windows no longer records which apps you open to rank Start suggestions.',
    [dw(CV + '\\Explorer\\Advanced', 'Start_TrackProgs', 0)]),
  T('fast-shutdown', 'performance', 2, 'Close frozen apps and services faster', 'Cuts the wait before Windows force-closes frozen apps and services at shutdown to 2 seconds. Unsaved work in a frozen app is lost sooner.',
    [sz('HKCU\\Control Panel\\Desktop', 'WaitToKillAppTimeout', 2000), sz('HKCU\\Control Panel\\Desktop', 'HungAppTimeout', 2000), sz(CTL, 'WaitToKillServiceTimeout', 2000)], SO),
  T('ntfs-lastaccess', 'performance', 2, 'Stop updating file access times', 'NTFS stops writing a timestamp every time a file is read, which cuts small disk writes.',
    [dw(CTL + '\\FileSystem', 'NtfsDisableLastAccessUpdate', 1)], RS),
  T('mpo-off', 'performance', 3, 'Disable Multiplane Overlay', 'A known workaround for stutter and flicker on some GPUs. Can slightly raise GPU use during video playback.',
    [dw('HKLM\\SOFTWARE\\Microsoft\\Windows\\Dwm', 'OverlayTestMode', 5)], RS),
  T('paging-exec', 'performance', 3, 'Keep the kernel and drivers in RAM', 'Stops Windows paging core components out to disk. Only worth it with 16 GB of RAM or more.',
    [dw(CTL + '\\Session Manager\\Memory Management', 'DisablePagingExecutive', 1)], RS),
  T('spooler', 'performance', 3, 'Disable Print Spooler', 'Removes a background service and some attack surface if you never print. Printing stops working until you turn it back on.',
    [svc('Spooler')]),
  T('bluetooth-svc', 'performance', 3, 'Disable Bluetooth services', 'Only for PCs that use no Bluetooth mouse, headset or controller. Wireless devices stop connecting.',
    [svc('bthserv', 1), svc('BTAGService', 1)]),
  T('touch-keyboard', 'input', 2, 'Disable the touch keyboard service', 'For PCs without a touch screen or pen. The on-screen keyboard and handwriting stop working.',
    [svc('TabletInputService', 1)]),
  T('copilot-off', 'debloat', 1, 'Turn off Copilot', 'Hides Copilot and stops its background process on builds that honour the policy.',
    [dw('HKCU\\Software\\Policies\\Microsoft\\Windows\\WindowsCopilot', 'TurnOffWindowsCopilot', 1)], SO),
  T('lockscreen-ads', 'debloat', 1, 'Turn off lock screen tips and ads', 'The lock screen stops rotating Spotlight pictures with promotional overlays.',
    [dw(CDM, 'RotatingLockScreenEnabled', 0), dw(CDM, 'RotatingLockScreenOverlayEnabled', 0)]),
  T('toasts-off', 'debloat', 2, 'Turn off notification pop-ups', "No app notifications appear over your game. You won't see messages until you turn this back on.",
    [dw(CV + '\\PushNotifications', 'ToastEnabled', 0)]),
  T('edge-background', 'debloat', 2, 'Stop Edge running in the background', 'Edge no longer preloads at sign-in or stays running after you close it. Edge may show "managed by your organization".',
    [dw('HKLM\\SOFTWARE\\Policies\\Microsoft\\Edge', 'StartupBoostEnabled', 0), dw('HKLM\\SOFTWARE\\Policies\\Microsoft\\Edge', 'BackgroundModeEnabled', 0)]),
  T('minor-services', 'debloat', 2, 'Disable rarely used services', 'Turns off the Fax, Downloaded Maps, Retail Demo, Wallet, Windows Insider, Phone and WAP Push services. They sit idle on most PCs.',
    [svc('Fax', 1), svc('MapsBroker', 1), svc('RetailDemo', 1), svc('WalletService', 1), svc('wisvc', 1), svc('PhoneSvc', 1), svc('dmwappushservice', 1)]),
  T('onedrive-off', 'debloat', 3, 'Disable OneDrive', 'Stops OneDrive running and syncing. Files already synced stay on the PC, but nothing new uploads.',
    [dw(POL + '\\OneDrive', 'DisableFileSyncNGSC', 1)], SO)
];
